export enum OrderState {
  CREATED = 'CREATED',
  RESERVING = 'RESERVING',
  RESERVED = 'RESERVED',
  VALIDATING = 'VALIDATING',
  CANCELING = 'CANCELING',
  CANCELED = 'CANCELED',
  DISPATCHING = 'DISPATCHING',
  RESTOCKING = 'RESTOCKING',
  DISPATCHED = 'DISPATCHED',
  DELIVERED = 'DELIVERED',
}
