name: CI Monorepo

on:
  push:
    branches: [ main, develop , feature/Central-System-Microservice ]
  pull_request:
    branches: [ main, develop , feature/Central-System-Microservice ]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22.16.0
          cache: npm
          cache-dependency-path: |
            microservices/warehouse/package-lock.json
            microservices/warehouse-aggregator/package-lock.json

      - name: Start services with Docker Compose
        run: |
          docker compose up -d
          echo "Waiting for MongoDB and NATS to be ready..."
          sleep 10

      # Install root dependencies
      - name: Install root dependencies
        working-directory: microservices
        run: npm install

      # Warehouse

      - name: Install Warehouse dependencies
        working-directory: microservices/warehouse
        run: npm ci

      - name: Run Warehouse tests
        working-directory: microservices/warehouse
        run: npm run test:cov

      - name: Upload Warehouse coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: microservices/warehouse/coverage/lcov.info
          flags: warehouse
          name: warehouse
          fail_ci_if_error: true

      # Warehouse Aggregator

      - name: Install Warehouse Aggregator dependencies
        working-directory: microservices/warehouse-aggregator
        run: npm ci

      - name: Run Warehouse Aggregator tests
        working-directory: microservices/warehouse-aggregator
        run: npm run test:cov

      - name: Upload Warehouse Aggregator coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: microservices/warehouse-aggregator/coverage/lcov.info
          flags: warehouse-aggregator
          name: warehouse-aggregator
          fail_ci_if_error: true

      # CentralSystem
      - name: Install CentralSystem dependencies
        working-directory: microservices/centralized/CentralSystem
        run: npm install || echo "No tests for centralSystem"

      - name: Debug file names
        run: ls -R microservices/centralized/CentralSystem/src/interfaces/http/dto


      - name: Run CentralSystem tests
        working-directory: microservices/centralized/CentralSystem
        run: npm run test:cov

      - name: Check CentralSystem coverage
        run: ls -lah microservices/centralized/CentralSystem/coverage

      - name: Upload CentralSystem coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: microservices/centralized/CentralSystem/coverage/lcov.info
          flags: centralSystem
          name: centralSystem

      # Auth
      - name: Install Auth dependencies
        working-directory: microservices/centralized/authentication
        run: npm install || echo "No tests for authentication"

      - name: Run Auth tests
        working-directory: microservices/centralized/authentication
        run: npm run test:cov

      - name: Upload Auth coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: microservices/centralized/authentication/coverage/lcov.info
          flags: auth
          name: auth
  
      # Routing
      - name: Install Routing
        working-directory: microservices/centralized/routing
        run: npm install || echo "No tests for routing"

      - name: Run Routing tests
        working-directory: microservices/centralized/routing
        run: npm run test:cov || echo "No tests for routing"

      - name: Upload Routing coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: routing
          files: microservices/centralized/routing/coverage/lcov.info
          name: Routing

      # State Cloud
      - name: Install State Cloud
        working-directory: microservices/centralized/state_aggregate
        run: npm install || echo "No tests for Cloud State"

      - name: Run State Cloud tests
        working-directory: microservices/centralized/state_aggregate
        run: npm run test:cov || echo "No tests for Cloud State"

      - name: Upload State Cloud coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: CloudState
          files: microservices/centralized/state_aggregate/coverage/lcov.info
          name: Cloud State

      # Commit updated README
      - name: Commit updated README
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add README.md
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update README with latest test results"
            git push
          fi
